[package]
name = "advent-of-code-day-1-problem-1"
version = "1.0.0"
description = "Solution for Day 1 of Advent of Code 2021"
edition = "2021"
license = "CC0-1.0"

[[bin]]
name = "aocd11"
path = "src/main.rs"

[dependencies]
error-chain = "0.12"
